site_name: ArchCI
#site_url: /
use_absolute_urls: true
dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/ArchCI/archci
# site_description: ArchCI
copyright: Copyright &copy; 2015, <a href="https://github.com/ArchCI/archci">ArchCI</a>.

# docs_dir: en
docs_dir: zh

#include_search: true
#theme: readthedocs

pages:

# Home
- ['index.md', 'Home']

# Development

- ['development/architecture.md', 'Development', 'Architecture']
- ['development/start_archci.md', 'Development', 'Start archci']
- ['development/start_worker.md', 'Development', 'Start worker']


# User Guide
- ['user_guide/installation.md', 'User Guide', 'Installation']

# Worker
- ['worker/usage.md', 'Worker', 'Usage']

# Client
- ['client/usage.md', 'Client', 'Usage']