site_name: ArchCI
#site_url: /
use_absolute_urls: true
dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/ArchCI/archci
# site_description: ArchCI
copyright: Copyright &copy; 2015, <a href="https://github.com/ArchCI/archci">ArchCI</a>.

# docs_dir: en
docs_dir: zh

#include_search: true
#theme: readthedocs

pages:

# Home
- ['index.md', '首页']

# Development

- ['development/introduction.md', '开发指南', '项目简介']
- ['development/architecture.md', '开发指南', '系统结构']
- ['development/archci.md', '开发指南', 'archci详解']
- ['development/worker.md', '开发指南', 'worker详解']

# User Guide
- ['user_guide/installation.md', '用户指南', '安装指南']
- ['user_guide/aci_usage.md', '用户指南', 'aci用法']
