site_name: ArchCI
#site_url: /
use_absolute_urls: true
dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/ArchCI/archci
# site_description: ArchCI
copyright: Copyright &copy; 2015, <a href="https://github.com/ArchCI/archci">ArchCI</a>.

# docs_dir: en
docs_dir: zh

#include_search: true
#theme: readthedocs

pages:

# Home
- ['index.md', 'Home']

# Development

- ['development/introduction.md', '开发指南', '项目简介']
- ['development/start_archci.md', '开发指南', '启动archci']
- ['development/start_worker.md', '开发指南', '启动worker']

# User Guide
- ['user_guide/installation.md', '用户指南', '安装指南']

# Worker
- ['worker/usage.md', '后端', '使用方法']

# Client
- ['client/usage.md', '客户端', '使用方法']