site_name: ArchCI
site_url: /
use_absolute_urls: true
dev_addr: '0.0.0.0:8000'

repo_url: https://github.com/ArchCI/archci
# site_description: ArchCI
copyright: Copyright &copy; 2015, <a href="https://github.com/ArchCI/archci">ArchCI</a>.

docs_dir: zh
# docs_dir: en

#include_search: true
#theme: readthedocs

pages:

# Home
- ['index.md', 'Home']

# User Guide
- ['user_guide/installation.md', 'User Guide', 'Installation']

